/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.engine.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CTEChangeCollection service. Represents a row in the &quot;CTEChangeCollection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.change.tracking.engine.model.impl.CTEChangeCollectionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.change.tracking.engine.model.impl.CTEChangeCollectionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CTEChangeCollection
 * @see com.liferay.change.tracking.engine.model.impl.CTEChangeCollectionImpl
 * @see com.liferay.change.tracking.engine.model.impl.CTEChangeCollectionModelImpl
 * @generated
 */
@ProviderType
public interface CTEChangeCollectionModel extends AuditedModel,
	BaseModel<CTEChangeCollection>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cte change collection model instance should use the {@link CTEChangeCollection} interface instead.
	 */

	/**
	 * Returns the primary key of this cte change collection.
	 *
	 * @return the primary key of this cte change collection
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cte change collection.
	 *
	 * @param primaryKey the primary key of this cte change collection
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the cte change collection ID of this cte change collection.
	 *
	 * @return the cte change collection ID of this cte change collection
	 */
	public long getCteChangeCollectionId();

	/**
	 * Sets the cte change collection ID of this cte change collection.
	 *
	 * @param cteChangeCollectionId the cte change collection ID of this cte change collection
	 */
	public void setCteChangeCollectionId(long cteChangeCollectionId);

	/**
	 * Returns the company ID of this cte change collection.
	 *
	 * @return the company ID of this cte change collection
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this cte change collection.
	 *
	 * @param companyId the company ID of this cte change collection
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this cte change collection.
	 *
	 * @return the user ID of this cte change collection
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this cte change collection.
	 *
	 * @param userId the user ID of this cte change collection
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cte change collection.
	 *
	 * @return the user uuid of this cte change collection
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cte change collection.
	 *
	 * @param userUuid the user uuid of this cte change collection
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cte change collection.
	 *
	 * @return the user name of this cte change collection
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this cte change collection.
	 *
	 * @param userName the user name of this cte change collection
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this cte change collection.
	 *
	 * @return the create date of this cte change collection
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this cte change collection.
	 *
	 * @param createDate the create date of this cte change collection
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cte change collection.
	 *
	 * @return the modified date of this cte change collection
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cte change collection.
	 *
	 * @param modifiedDate the modified date of this cte change collection
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this cte change collection.
	 *
	 * @return the name of this cte change collection
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cte change collection.
	 *
	 * @param name the name of this cte change collection
	 */
	public void setName(String name);

	/**
	 * Returns the description of this cte change collection.
	 *
	 * @return the description of this cte change collection
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this cte change collection.
	 *
	 * @param description the description of this cte change collection
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CTEChangeCollection cteChangeCollection);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CTEChangeCollection> toCacheModel();

	@Override
	public CTEChangeCollection toEscapedModel();

	@Override
	public CTEChangeCollection toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}