/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.engine.uad.anonymizer;

import com.liferay.change.tracking.engine.model.CTEChangeEntry;
import com.liferay.change.tracking.engine.service.CTEChangeEntryLocalService;
import com.liferay.change.tracking.engine.uad.constants.ChangeTrackingEngineUADConstants;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;

import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the cte change entry UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link CTEChangeEntryUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseCTEChangeEntryUADAnonymizer
	extends DynamicQueryUADAnonymizer<CTEChangeEntry> {
	@Override
	public void autoAnonymize(CTEChangeEntry cteChangeEntry, long userId,
		User anonymousUser) throws PortalException {
		if (cteChangeEntry.getUserId() == userId) {
			cteChangeEntry.setUserId(anonymousUser.getUserId());
			cteChangeEntry.setUserName(anonymousUser.getFullName());
		}

		cteChangeEntryLocalService.updateCTEChangeEntry(cteChangeEntry);
	}

	@Override
	public void delete(CTEChangeEntry cteChangeEntry) throws PortalException {
		cteChangeEntryLocalService.deleteCTEChangeEntry(cteChangeEntry);
	}

	@Override
	public Class<CTEChangeEntry> getTypeClass() {
		return CTEChangeEntry.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return cteChangeEntryLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return ChangeTrackingEngineUADConstants.USER_ID_FIELD_NAMES_CTE_CHANGE_ENTRY;
	}

	@Reference
	protected CTEChangeEntryLocalService cteChangeEntryLocalService;
}