/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.engine.uad.anonymizer;

import com.liferay.change.tracking.engine.model.CTEChangeCollection;
import com.liferay.change.tracking.engine.service.CTEChangeCollectionLocalService;
import com.liferay.change.tracking.engine.uad.constants.ChangeTrackingEngineUADConstants;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;

import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the cte change collection UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link CTEChangeCollectionUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseCTEChangeCollectionUADAnonymizer
	extends DynamicQueryUADAnonymizer<CTEChangeCollection> {
	@Override
	public void autoAnonymize(CTEChangeCollection cteChangeCollection,
		long userId, User anonymousUser) throws PortalException {
		if (cteChangeCollection.getUserId() == userId) {
			cteChangeCollection.setUserId(anonymousUser.getUserId());
			cteChangeCollection.setUserName(anonymousUser.getFullName());
		}

		cteChangeCollectionLocalService.updateCTEChangeCollection(cteChangeCollection);
	}

	@Override
	public void delete(CTEChangeCollection cteChangeCollection)
		throws PortalException {
		cteChangeCollectionLocalService.deleteCTEChangeCollection(cteChangeCollection);
	}

	@Override
	public Class<CTEChangeCollection> getTypeClass() {
		return CTEChangeCollection.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return cteChangeCollectionLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return ChangeTrackingEngineUADConstants.USER_ID_FIELD_NAMES_CTE_CHANGE_COLLECTION;
	}

	@Reference
	protected CTEChangeCollectionLocalService cteChangeCollectionLocalService;
}