/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.engine.uad.exporter;

import com.liferay.change.tracking.engine.model.CTEChangeCollection;
import com.liferay.change.tracking.engine.service.CTEChangeCollectionLocalService;
import com.liferay.change.tracking.engine.uad.constants.ChangeTrackingEngineUADConstants;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.util.StringBundler;

import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the cte change collection UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link CTEChangeCollectionUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseCTEChangeCollectionUADExporter
	extends DynamicQueryUADExporter<CTEChangeCollection> {
	@Override
	public Class<CTEChangeCollection> getTypeClass() {
		return CTEChangeCollection.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return cteChangeCollectionLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return ChangeTrackingEngineUADConstants.USER_ID_FIELD_NAMES_CTE_CHANGE_COLLECTION;
	}

	@Override
	protected String toXmlString(CTEChangeCollection cteChangeCollection) {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.change.tracking.engine.model.CTEChangeCollection");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cteChangeCollectionId</column-name><column-value><![CDATA[");
		sb.append(cteChangeCollection.getCteChangeCollectionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(cteChangeCollection.getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(cteChangeCollection.getUserName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	@Reference
	protected CTEChangeCollectionLocalService cteChangeCollectionLocalService;
}