/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.exportimport.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EntityPublication service. Represents a row in the &quot;EntityPublication&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.exportimport.model.impl.EntityPublicationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.exportimport.model.impl.EntityPublicationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntityPublication
 * @see com.liferay.exportimport.model.impl.EntityPublicationImpl
 * @see com.liferay.exportimport.model.impl.EntityPublicationModelImpl
 * @generated
 */
@ProviderType
public interface EntityPublicationModel extends AttachedModel, AuditedModel,
	BaseModel<EntityPublication>, MVCCModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a entity publication model instance should use the {@link EntityPublication} interface instead.
	 */

	/**
	 * Returns the primary key of this entity publication.
	 *
	 * @return the primary key of this entity publication
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this entity publication.
	 *
	 * @param primaryKey the primary key of this entity publication
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this entity publication.
	 *
	 * @return the mvcc version of this entity publication
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this entity publication.
	 *
	 * @param mvccVersion the mvcc version of this entity publication
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ID of this entity publication.
	 *
	 * @return the ID of this entity publication
	 */
	public long getId();

	/**
	 * Sets the ID of this entity publication.
	 *
	 * @param id the ID of this entity publication
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this entity publication.
	 *
	 * @return the company ID of this entity publication
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this entity publication.
	 *
	 * @param companyId the company ID of this entity publication
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this entity publication.
	 *
	 * @return the user ID of this entity publication
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this entity publication.
	 *
	 * @param userId the user ID of this entity publication
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this entity publication.
	 *
	 * @return the user uuid of this entity publication
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this entity publication.
	 *
	 * @param userUuid the user uuid of this entity publication
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this entity publication.
	 *
	 * @return the user name of this entity publication
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this entity publication.
	 *
	 * @param userName the user name of this entity publication
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this entity publication.
	 *
	 * @return the create date of this entity publication
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this entity publication.
	 *
	 * @param createDate the create date of this entity publication
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this entity publication.
	 *
	 * @return the modified date of this entity publication
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this entity publication.
	 *
	 * @param modifiedDate the modified date of this entity publication
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this entity publication.
	 *
	 * @return the fully qualified class name of this entity publication
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this entity publication.
	 *
	 * @return the class name ID of this entity publication
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this entity publication.
	 *
	 * @param classNameId the class name ID of this entity publication
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this entity publication.
	 *
	 * @return the class pk of this entity publication
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this entity publication.
	 *
	 * @param classPK the class pk of this entity publication
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the publication date of this entity publication.
	 *
	 * @return the publication date of this entity publication
	 */
	public Date getPublicationDate();

	/**
	 * Sets the publication date of this entity publication.
	 *
	 * @param publicationDate the publication date of this entity publication
	 */
	public void setPublicationDate(Date publicationDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EntityPublication entityPublication);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EntityPublication> toCacheModel();

	@Override
	public EntityPublication toEscapedModel();

	@Override
	public EntityPublication toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}