/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.engine.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.change.tracking.engine.model.CTEChangeEntry;
import com.liferay.change.tracking.engine.service.CTEChangeEntryLocalServiceUtil;

/**
 * The extended model base implementation for the CTEChangeEntry service. Represents a row in the &quot;CTEChangeEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CTEChangeEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CTEChangeEntryImpl
 * @see CTEChangeEntry
 * @generated
 */
@ProviderType
public abstract class CTEChangeEntryBaseImpl extends CTEChangeEntryModelImpl
	implements CTEChangeEntry {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cte change entry model instance should use the {@link CTEChangeEntry} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CTEChangeEntryLocalServiceUtil.addCTEChangeEntry(this);
		}
		else {
			CTEChangeEntryLocalServiceUtil.updateCTEChangeEntry(this);
		}
	}
}