/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.engine.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.change.tracking.engine.model.CTEChangeEntry;
import com.liferay.change.tracking.engine.model.CTEChangeEntryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CTEChangeEntry service. Represents a row in the &quot;CTEChangeEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CTEChangeEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CTEChangeEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CTEChangeEntryImpl
 * @see CTEChangeEntry
 * @see CTEChangeEntryModel
 * @generated
 */
@ProviderType
public class CTEChangeEntryModelImpl extends BaseModelImpl<CTEChangeEntry>
	implements CTEChangeEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cte change entry model instance should use the {@link CTEChangeEntry} interface instead.
	 */
	public static final String TABLE_NAME = "CTEChangeEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "cteChangeEntryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "classNameId", Types.BIGINT },
			{ "classPK", Types.BIGINT },
			{ "resourcePrimKey", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("cteChangeEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resourcePrimKey", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table CTEChangeEntry (cteChangeEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,resourcePrimKey LONG)";
	public static final String TABLE_SQL_DROP = "drop table CTEChangeEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY cteChangeEntry.cteChangeEntryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CTEChangeEntry.cteChangeEntryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.change.tracking.engine.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.change.tracking.engine.model.CTEChangeEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.change.tracking.engine.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.change.tracking.engine.model.CTEChangeEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.change.tracking.engine.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.change.tracking.engine.model.CTEChangeEntry"),
			true);
	public static final long RESOURCEPRIMKEY_COLUMN_BITMASK = 1L;
	public static final long CTECHANGEENTRYID_COLUMN_BITMASK = 2L;
	public static final String MAPPING_TABLE_COLLECTIONS_ENTRIES_NAME = "Collections_Entries";
	public static final Object[][] MAPPING_TABLE_COLLECTIONS_ENTRIES_COLUMNS = {
			{ "companyId", Types.BIGINT },
			{ "cteChangeCollectionId", Types.BIGINT },
			{ "cteChangeEntryId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_COLLECTIONS_ENTRIES_SQL_CREATE = "create table Collections_Entries (companyId LONG not null,cteChangeCollectionId LONG not null,cteChangeEntryId LONG not null,primary key (cteChangeCollectionId, cteChangeEntryId))";
	public static final boolean FINDER_CACHE_ENABLED_COLLECTIONS_ENTRIES = GetterUtil.getBoolean(com.liferay.change.tracking.engine.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.Collections_Entries"), true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.change.tracking.engine.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.change.tracking.engine.model.CTEChangeEntry"));

	public CTEChangeEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cteChangeEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCteChangeEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cteChangeEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CTEChangeEntry.class;
	}

	@Override
	public String getModelClassName() {
		return CTEChangeEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("cteChangeEntryId", getCteChangeEntryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("classNameId", getClassNameId());
		attributes.put("classPK", getClassPK());
		attributes.put("resourcePrimKey", getResourcePrimKey());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long cteChangeEntryId = (Long)attributes.get("cteChangeEntryId");

		if (cteChangeEntryId != null) {
			setCteChangeEntryId(cteChangeEntryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long classNameId = (Long)attributes.get("classNameId");

		if (classNameId != null) {
			setClassNameId(classNameId);
		}

		Long classPK = (Long)attributes.get("classPK");

		if (classPK != null) {
			setClassPK(classPK);
		}

		Long resourcePrimKey = (Long)attributes.get("resourcePrimKey");

		if (resourcePrimKey != null) {
			setResourcePrimKey(resourcePrimKey);
		}
	}

	@Override
	public long getCteChangeEntryId() {
		return _cteChangeEntryId;
	}

	@Override
	public void setCteChangeEntryId(long cteChangeEntryId) {
		_cteChangeEntryId = cteChangeEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_classPK = classPK;
	}

	@Override
	public long getResourcePrimKey() {
		return _resourcePrimKey;
	}

	@Override
	public void setResourcePrimKey(long resourcePrimKey) {
		_columnBitmask |= RESOURCEPRIMKEY_COLUMN_BITMASK;

		if (!_setOriginalResourcePrimKey) {
			_setOriginalResourcePrimKey = true;

			_originalResourcePrimKey = _resourcePrimKey;
		}

		_resourcePrimKey = resourcePrimKey;
	}

	@Override
	public boolean isResourceMain() {
		return true;
	}

	public long getOriginalResourcePrimKey() {
		return _originalResourcePrimKey;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CTEChangeEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CTEChangeEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CTEChangeEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CTEChangeEntryImpl cteChangeEntryImpl = new CTEChangeEntryImpl();

		cteChangeEntryImpl.setCteChangeEntryId(getCteChangeEntryId());
		cteChangeEntryImpl.setCompanyId(getCompanyId());
		cteChangeEntryImpl.setUserId(getUserId());
		cteChangeEntryImpl.setUserName(getUserName());
		cteChangeEntryImpl.setCreateDate(getCreateDate());
		cteChangeEntryImpl.setModifiedDate(getModifiedDate());
		cteChangeEntryImpl.setClassNameId(getClassNameId());
		cteChangeEntryImpl.setClassPK(getClassPK());
		cteChangeEntryImpl.setResourcePrimKey(getResourcePrimKey());

		cteChangeEntryImpl.resetOriginalValues();

		return cteChangeEntryImpl;
	}

	@Override
	public int compareTo(CTEChangeEntry cteChangeEntry) {
		long primaryKey = cteChangeEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CTEChangeEntry)) {
			return false;
		}

		CTEChangeEntry cteChangeEntry = (CTEChangeEntry)obj;

		long primaryKey = cteChangeEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CTEChangeEntryModelImpl cteChangeEntryModelImpl = this;

		cteChangeEntryModelImpl._setModifiedDate = false;

		cteChangeEntryModelImpl._originalResourcePrimKey = cteChangeEntryModelImpl._resourcePrimKey;

		cteChangeEntryModelImpl._setOriginalResourcePrimKey = false;

		cteChangeEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CTEChangeEntry> toCacheModel() {
		CTEChangeEntryCacheModel cteChangeEntryCacheModel = new CTEChangeEntryCacheModel();

		cteChangeEntryCacheModel.cteChangeEntryId = getCteChangeEntryId();

		cteChangeEntryCacheModel.companyId = getCompanyId();

		cteChangeEntryCacheModel.userId = getUserId();

		cteChangeEntryCacheModel.userName = getUserName();

		String userName = cteChangeEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cteChangeEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cteChangeEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			cteChangeEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cteChangeEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cteChangeEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cteChangeEntryCacheModel.classNameId = getClassNameId();

		cteChangeEntryCacheModel.classPK = getClassPK();

		cteChangeEntryCacheModel.resourcePrimKey = getResourcePrimKey();

		return cteChangeEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{cteChangeEntryId=");
		sb.append(getCteChangeEntryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", classNameId=");
		sb.append(getClassNameId());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append(", resourcePrimKey=");
		sb.append(getResourcePrimKey());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.change.tracking.engine.model.CTEChangeEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>cteChangeEntryId</column-name><column-value><![CDATA[");
		sb.append(getCteChangeEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classNameId</column-name><column-value><![CDATA[");
		sb.append(getClassNameId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>resourcePrimKey</column-name><column-value><![CDATA[");
		sb.append(getResourcePrimKey());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CTEChangeEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CTEChangeEntry.class, ModelWrapper.class
		};
	private long _cteChangeEntryId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _classPK;
	private long _resourcePrimKey;
	private long _originalResourcePrimKey;
	private boolean _setOriginalResourcePrimKey;
	private long _columnBitmask;
	private CTEChangeEntry _escapedModel;
}